import React, { useEffect, useState } from 'react';
import apiClient from '../../services/apiClient';
import toast from 'react-hot-toast';

const blank = { slug: '', title: '', author: 'Dr Sweta Adatia', category: 'general', thumbnail_url: '', course_url: '', original_price: '', sale_price: '', currency: 'INR', is_free: false, is_visible: true, sort_order: 0 };
export default function BrainCoursesSetup() {
  const [courses, setCourses] = useState([]); const [editing, setEditing] = useState(null);
  const load = () => apiClient.get('/brain-courses/admin').then(({ data }) => setCourses(data.courses || [])).catch(() => toast.error('Courses could not be loaded.'));
  useEffect(() => { load(); }, []);
  const save = async (event) => { event.preventDefault(); try { const { id, ...course } = editing; await (id ? apiClient.patch(`/brain-courses/admin/${id}`, course) : apiClient.post('/brain-courses/admin', course)); setEditing(null); load(); toast.success('Course saved.'); } catch (error) { toast.error(error.message || 'Course could not be saved.'); } };
  return <div className="max-w-5xl space-y-5"><div className="flex justify-between items-center"><div><h2 className="text-xl font-bold">Patient Brain Courses</h2><p className="text-sm text-gray-500">Changes appear automatically in the patient portal.</p></div><button className="bg-[#323956] text-white px-4 py-2 rounded-lg" onClick={() => setEditing(blank)}>Add course</button></div>{editing && <form onSubmit={save} className="grid grid-cols-1 md:grid-cols-2 gap-3 bg-white p-4 rounded-xl border">{['slug', 'title', 'author', 'category', 'thumbnail_url', 'course_url', 'original_price', 'sale_price', 'currency', 'sort_order'].map((field) => <label key={field} className="text-sm capitalize">{field.replace(/_/g, ' ')}<input required={['slug','title','course_url','currency'].includes(field)} value={editing[field] ?? ''} type={field.includes('price') || field === 'sort_order' ? 'number' : 'text'} onChange={(e) => setEditing({ ...editing, [field]: e.target.value })} className="mt-1 w-full border rounded p-2" /></label>)}<label className="flex gap-2 items-center"><input type="checkbox" checked={editing.is_free} onChange={(e) => setEditing({ ...editing, is_free: e.target.checked, sale_price: e.target.checked ? '' : editing.sale_price })} />Free course</label><label className="flex gap-2 items-center"><input type="checkbox" checked={editing.is_visible} onChange={(e) => setEditing({ ...editing, is_visible: e.target.checked })} />Visible to patients</label><div className="md:col-span-2 flex gap-2"><button className="bg-green-600 text-white px-4 py-2 rounded">Save</button><button type="button" onClick={() => setEditing(null)} className="border px-4 py-2 rounded">Cancel</button></div></form>}<div className="bg-white border rounded-xl divide-y">{courses.map((course) => <button key={course.id} onClick={() => setEditing(course)} className="w-full text-left p-4 hover:bg-gray-50 flex justify-between gap-3"><span><strong>{course.title}</strong><small className="block text-gray-500">{course.currency} {course.sale_price || 'Free'} · {course.is_visible ? 'Visible' : 'Hidden'}</small></span><span className="text-blue-600">Edit</span></button>)}</div></div>;
}
