// KSB NSB — All 27 Combinations (3 Parameters × 3 Levels)
// P1 = Cognition composite, P2 = Stress & Burnout composite, P3 = Emotional Regulation
// Source: KSB_27_Combinations.xlsx — "All 27 Combinations" sheet

const KSB_27_COMBINATIONS = {
  'L-L-L': { code: 'L-L-L', severity: 21, priority: 'HIGH', description: 'Triple Low — unusual profile. Assess for anhedonia or dissociation. Gentle activation needed.', pranayama: 'Bhramari + Chandra Bhedi', yogasana: 'Ushtrasana (Camel Pose) + Tadasana (Mountain Pose)', meditation: 'Anxiety Meditation', binaural: 'Solfeggio 639 Hz · 20 min PM', chant: 'Saraswati Mantra', supplement1: 'Happy Brain · 1 cap · AM', supplement2: 'Aswa Extract + Acetyl Carnie Pearl' },
  'L-L-M': { code: 'L-L-M', severity: 16, priority: 'HIGH', description: 'Cognitive & Partial ER deficit — low stress. Targeted cognition + ER maintenance.', pranayama: 'Kapalbhati + Anulom Vilom', yogasana: 'Marjaryasana-Bitilasana (Cat Cow) + Viparita Karani', meditation: 'Memory Meditation', binaural: 'Alpha Binaural 8–12 Hz · 20 min AM', chant: 'Gayatri Mantra', supplement1: 'Acetyl Carnie Pearl · 500mg–1g · AM fasted', supplement2: 'P-Serine + Happy Brain' },
  'L-L-H': { code: 'L-L-H', severity: 12, priority: 'MODERATE', description: 'Isolated Cognitive Deficit — all else optimal. Pure cognitive activation protocol.', pranayama: 'Kapalbhati + Ujjayi', yogasana: 'Marjaryasana-Bitilasana (Cat Cow) + Viparita Karani', meditation: 'Memory Meditation', binaural: 'Alpha Binaural 8–12 Hz · 20 min AM', chant: 'Gayatri Mantra', supplement1: 'Acetyl Carnie Pearl · 500mg–1g · AM fasted', supplement2: 'P-Serine + Happy Brain' },
  'L-M-L': { code: 'L-M-L', severity: 25, priority: 'CRITICAL', description: 'Cognitive & Emotional Deficit — stress manageable. Focus: acetylcholine + serotonin rebuild.', pranayama: 'Bhramari + Chandra Bhedi', yogasana: 'Ushtrasana (Camel Pose) + Tadasana (Mountain Pose)', meditation: 'Anxiety Meditation', binaural: 'Solfeggio 639 Hz · 20 min PM', chant: 'Saraswati Mantra', supplement1: 'Happy Brain · 1 cap · AM', supplement2: 'Aswa Extract + Acetyl Carnie Pearl' },
  'L-M-M': { code: 'L-M-M', severity: 20, priority: 'HIGH', description: 'Cognitive Primary Deficit — balanced stress/ER. Focus: brain energy and encoding.', pranayama: 'Kapalbhati + Anulom Vilom', yogasana: 'Marjaryasana-Bitilasana (Cat Cow) + Viparita Karani', meditation: 'Memory Meditation', binaural: 'Alpha Binaural 8–12 Hz · 20 min AM', chant: 'Gayatri Mantra', supplement1: 'Acetyl Carnie Pearl · 500mg–1g · AM fasted', supplement2: 'P-Serine + Happy Brain' },
  'L-M-H': { code: 'L-M-H', severity: 16, priority: 'HIGH', description: 'Cognitive Deficit Only — stress and emotion stable. Pure cognition protocol.', pranayama: "Kapalbhati + Bahya Kumbhak", yogasana: "Marjaryasana-Bitilasana (Cat Cow) + Balasana (Child's Pose)", meditation: 'Memory Meditation', binaural: 'Alpha Binaural 8–12 Hz · 20 min AM', chant: 'Gayatri Mantra', supplement1: 'Acetyl Carnie Pearl · 500mg–1g · AM fasted', supplement2: 'P-Serine + Magneshine G' },
  'L-H-L': { code: 'L-H-L', severity: 30, priority: 'CRITICAL', description: 'Complete Depletion — cognitive fog + burnout + emotional dysregulation. Priority: stabilise stress first.', pranayama: 'Bhramari + Yogic Breathing', yogasana: 'Ushtrasana (Camel Pose) + Saral Matsyana (Simple Fish)', meditation: 'Anxiety Meditation', binaural: 'Solfeggio 639 Hz · 20 min PM', chant: 'Saraswati Mantra', supplement1: 'Happy Brain · 1 cap · AM', supplement2: 'Aswa Extract + Magneshine G' },
  'L-H-M': { code: 'L-H-M', severity: 25, priority: 'CRITICAL', description: 'Cognitive & Burnout Primary — emotional partially intact. Focus: NAD+ restore + HPA reset.', pranayama: 'Box Breathing + Chandra Bhedi', yogasana: 'Viparita Karani (Legs Up Wall) + Tadasana (Mountain Pose)', meditation: 'Yoga Nidra', binaural: 'Solfeggio 174 Hz · 20–30 min PM', chant: 'Gang Beej', supplement1: 'Magneshine G · 26 mg · PM', supplement2: 'Tryptoplus + Acetyl Carnie Pearl' },
  'L-H-H': { code: 'L-H-H', severity: 21, priority: 'HIGH', description: 'Cognitive Deficit with High Burnout — emotional strong. Focus: burnout recovery + cognition rebuild.', pranayama: 'Box Breathing + Chandra Bhedi', yogasana: 'Viparita Karani (Legs Up Wall) + Tadasana (Mountain Pose)', meditation: 'Yoga Nidra', binaural: 'Solfeggio 174 Hz · 20–30 min PM', chant: 'Gang Beej', supplement1: 'Magneshine G · 26 mg · PM', supplement2: 'Tryptoplus + Acetyl Carnie Pearl' },
  'M-L-L': { code: 'M-L-L', severity: 16, priority: 'HIGH', description: 'ER Deficit + Low Stress — cognition moderate. Emotional regulation as primary protocol.', pranayama: 'Bhramari + Bhramari', yogasana: 'Ushtrasana (Camel Pose) + Vrikshasana (Tree Pose)', meditation: 'Anxiety Meditation', binaural: 'Solfeggio 639 Hz · 20 min PM', chant: 'Saraswati Mantra', supplement1: 'Happy Brain · 1 cap · AM', supplement2: 'Aswa Extract + Vin-O-Neuro' },
  'M-L-M': { code: 'M-L-M', severity: 11, priority: 'MODERATE', description: 'Moderate Cognition — low stress and ER. Cognitive enhancement and ER maintenance.', pranayama: 'Bhramari + Bhramari', yogasana: 'Ushtrasana (Camel Pose) + Vrikshasana (Tree Pose)', meditation: 'PTSD Meditation', binaural: 'Solfeggio 639 Hz · 20 min PM', chant: 'Aim Beej', supplement1: 'Happy Brain · 1 cap · AM', supplement2: 'Aswa Extract + Vin-O-Neuro' },
  'M-L-H': { code: 'M-L-H', severity: 7, priority: 'OPTIMAL', description: 'Cognitive Moderate — optimal stress and ER. Cognitive performance upgrade focus.', pranayama: 'Anulom Vilom + Ujjayi', yogasana: 'Marjaryasana-Bitilasana (Cat Cow) + Viparita Karani', meditation: 'Gamma Meditation', binaural: '40 Hz Gamma Binaural · 20 min AM', chant: 'Gayatri Mantra', supplement1: 'Vin-O-Neuro · 10–20mg · AM with food', supplement2: 'Happy Brain' },
  'M-M-L': { code: 'M-M-L', severity: 20, priority: 'HIGH', description: 'ER Primary Deficit — balanced cognition and stress. Targeted emotional regulation protocol.', pranayama: 'Bhramari + Bahya Kumbhak', yogasana: "Ushtrasana (Camel Pose) + Balasana (Child's Pose)", meditation: 'Anxiety Meditation', binaural: 'Solfeggio 639 Hz · 20 min PM', chant: 'Saraswati Mantra', supplement1: 'Happy Brain · 1 cap · AM', supplement2: 'Aswa Extract + Magneshine G' },
  'M-M-M': { code: 'M-M-M', severity: 15, priority: 'MODERATE', description: 'Balanced Moderate — all three need work. Systematic all-round optimisation protocol.', pranayama: 'Bhramari + Bahya Kumbhak', yogasana: "Ushtrasana (Camel Pose) + Balasana (Child's Pose)", meditation: 'PTSD Meditation', binaural: 'Solfeggio 639 Hz · 20 min PM', chant: 'Aim Beej', supplement1: 'Happy Brain · 1 cap · AM', supplement2: 'Aswa Extract + Magneshine G' },
  'M-M-H': { code: 'M-M-H', severity: 11, priority: 'MODERATE', description: 'ER Optimal — cognition and stress moderate. Focus on stress management and cognition.', pranayama: 'Box Breathing + Bhramari', yogasana: 'Viparita Karani (Legs Up Wall) + Vrikshasana (Tree Pose)', meditation: 'Stress Relief Meditation', binaural: 'Solfeggio 528 Hz · 25 min PM', chant: 'Aum Gang Ganpataye Namah', supplement1: 'Magneshine G · 26 mg · PM', supplement2: 'Happy Brain + Vin-O-Neuro' },
  'M-H-L': { code: 'M-H-L', severity: 25, priority: 'CRITICAL', description: 'Burnout & ER Crisis — cognition partially intact. Stress + emotional regulation priority.', pranayama: 'Bhramari + Yogic Breathing', yogasana: 'Ushtrasana (Camel Pose) + Saral Matsyana (Simple Fish)', meditation: 'Anxiety Meditation', binaural: 'Solfeggio 639 Hz · 20 min PM', chant: 'Saraswati Mantra', supplement1: 'Happy Brain · 1 cap · AM', supplement2: 'Aswa Extract + Magneshine G' },
  'M-H-M': { code: 'M-H-M', severity: 20, priority: 'HIGH', description: 'Burnout Dominant — moderate cognition and ER. Full burnout protocol with moderate support.', pranayama: 'Box Breathing + Anulom Vilom', yogasana: 'Viparita Karani (Legs Up Wall) + Viparita Karani', meditation: 'Yoga Nidra', binaural: 'Solfeggio 174 Hz · 20–30 min PM', chant: 'Gang Beej', supplement1: 'Magneshine G · 26 mg · PM', supplement2: 'Tryptoplus + Happy Brain' },
  'M-H-H': { code: 'M-H-H', severity: 16, priority: 'HIGH', description: 'High Burnout — cognition and ER both stable. Focused burnout recovery.', pranayama: 'Box Breathing + Bhramari', yogasana: 'Viparita Karani (Legs Up Wall) + Vrikshasana (Tree Pose)', meditation: 'Yoga Nidra', binaural: 'Solfeggio 174 Hz · 20–30 min PM', chant: 'Gang Beej', supplement1: 'Magneshine G · 26 mg · PM', supplement2: 'Tryptoplus + Vin-O-Neuro' },
  'H-L-L': { code: 'H-L-L', severity: 12, priority: 'MODERATE', description: 'Peak Cognition + Low ER — minimal stress. Targeted emotional regulation uplift.', pranayama: 'Bhramari + Bhramari', yogasana: 'Ushtrasana (Camel Pose) + Surya Namaskar', meditation: 'Anxiety Meditation', binaural: 'Solfeggio 639 Hz · 20 min PM', chant: 'Saraswati Mantra', supplement1: 'Happy Brain · 1 cap · AM', supplement2: 'Aswa Extract + Synergy Multivitamin' },
  'H-L-M': { code: 'H-L-M', severity: 7, priority: 'OPTIMAL', description: 'Peak Cognition + Low Stress — ER moderate. Maintenance and emotional fine-tuning.', pranayama: 'Bhramari + Bhramari', yogasana: 'Ushtrasana (Camel Pose) + Surya Namaskar', meditation: 'PTSD Meditation', binaural: 'Solfeggio 639 Hz · 20 min PM', chant: 'Aim Beej', supplement1: 'Happy Brain · 1 cap · AM', supplement2: 'Aswa Extract + Synergy Multivitamin' },
  'H-L-H': { code: 'H-L-H', severity: 3, priority: 'OPTIMAL', description: 'All High / Optimal — Peak state across all three. Neuroprotection and longevity maintenance.', pranayama: 'Anulom Vilom + Bhramari', yogasana: 'Surya Namaskar + Surya Namaskar', meditation: 'Alpha Meditation', binaural: 'Solfeggio 852 Hz · 20 min AM', chant: 'Saraswati Mantra', supplement1: 'Happy Brain · 1 cap · AM', supplement2: '5 HTP + Synergy Multivitamin' },
  'H-M-L': { code: 'H-M-L', severity: 16, priority: 'HIGH', description: 'Peak Cognition + ER Deficit — stress moderate. ER regulation while sustaining cognitive peak.', pranayama: 'Bhramari + Bahya Kumbhak', yogasana: "Ushtrasana (Camel Pose) + Balasana (Child's Pose)", meditation: 'Anxiety Meditation', binaural: 'Solfeggio 639 Hz · 20 min PM', chant: 'Saraswati Mantra', supplement1: 'Happy Brain · 1 cap · AM', supplement2: 'Aswa Extract + Magneshine G' },
  'H-M-M': { code: 'H-M-M', severity: 11, priority: 'MODERATE', description: 'Peak Cognition — stress and ER moderate. Performance maintenance and stress prevention.', pranayama: 'Bhramari + Bahya Kumbhak', yogasana: "Ushtrasana (Camel Pose) + Balasana (Child's Pose)", meditation: 'PTSD Meditation', binaural: 'Solfeggio 639 Hz · 20 min PM', chant: 'Aim Beej', supplement1: 'Happy Brain · 1 cap · AM', supplement2: 'Aswa Extract + Magneshine G' },
  'H-M-H': { code: 'H-M-H', severity: 7, priority: 'OPTIMAL', description: 'High Cognition + ER — moderate stress. Stress management protocol to protect the peak.', pranayama: 'Box Breathing + Ujjayi', yogasana: 'Viparita Karani (Legs Up Wall) + Viparita Karani', meditation: 'Stress Relief Meditation', binaural: 'Solfeggio 528 Hz · 25 min PM', chant: 'Aum Gang Ganpataye Namah', supplement1: 'Magneshine G · 26 mg · PM', supplement2: 'Happy Brain' },
  'H-H-L': { code: 'H-H-L', severity: 21, priority: 'HIGH', description: 'High Cognition + Burnout + Low ER — burnout and ER dominate despite cognitive strength.', pranayama: 'Bhramari + Yogic Breathing', yogasana: 'Ushtrasana (Camel Pose) + Saral Matsyana (Simple Fish)', meditation: 'Anxiety Meditation', binaural: 'Solfeggio 639 Hz · 20 min PM', chant: 'Saraswati Mantra', supplement1: 'Happy Brain · 1 cap · AM', supplement2: 'Aswa Extract + Magneshine G' },
  'H-H-M': { code: 'H-H-M', severity: 16, priority: 'HIGH', description: 'Cognitive Peak + Burnout — ER moderate. Burnout recovery without losing cognitive edge.', pranayama: 'Box Breathing + Anulom Vilom', yogasana: 'Viparita Karani (Legs Up Wall) + Viparita Karani', meditation: 'Yoga Nidra', binaural: 'Solfeggio 174 Hz · 20–30 min PM', chant: 'Gang Beej', supplement1: 'Magneshine G · 26 mg · PM', supplement2: 'Tryptoplus + Happy Brain' },
  'H-H-H': { code: 'H-H-H', severity: 12, priority: 'MODERATE', description: 'High Cognition + Burnout — ER optimal. Focused burnout recovery with neuroprotection.', pranayama: 'Box Breathing + Ujjayi', yogasana: 'Viparita Karani (Legs Up Wall) + Viparita Karani', meditation: 'Yoga Nidra', binaural: 'Solfeggio 174 Hz · 20–30 min PM', chant: 'Gang Beej', supplement1: 'Magneshine G · 26 mg · PM', supplement2: 'Tryptoplus + Happy Brain' },
};

export default KSB_27_COMBINATIONS;
