import React, { useEffect, useMemo, useState } from 'react';
import { GraduationCap, ExternalLink, ChevronDown, Lock, ShoppingCart } from 'lucide-react';
import apiClient from '../services/apiClient';
import toast from 'react-hot-toast';

const money = (amount, currency) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: currency || 'INR', maximumFractionDigits: 0 }).format(amount || 0);

const BrainCourses = () => {
  const [courses, setCourses] = useState([]); const [owned, setOwned] = useState([]); const [category, setCategory] = useState('All'); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.allSettled([apiClient.get('/brain-courses'), apiClient.get('/brain-courses/access', { skipAuthRedirect: true })]).then(([catalog, access]) => { if (catalog.status === 'fulfilled') setCourses(catalog.value.data.courses || []); else toast.error('Courses could not be loaded.'); if (access.status === 'fulfilled') setOwned(access.value.data.courseIds || []); }).finally(() => setLoading(false)); }, []);
  const categories = useMemo(() => ['All', ...new Set(courses.map((course) => course.category).filter(Boolean))], [courses]);
  const buy = async (course) => { try { const { data } = await apiClient.post(`/brain-courses/${course.id}/checkout`, {}, { skipAuthRedirect: true }); window.location.assign(data.checkoutUrl); } catch (error) { toast.error(error.message || 'Checkout could not be started.'); } };
  const visible = category === 'All' ? courses : courses.filter((course) => course.category === category);
  return <div className="space-y-4 sm:space-y-6"><div className="bg-gradient-to-r from-[#323956] to-[#4a5578] rounded-xl p-4 sm:p-6 text-white"><div className="flex items-center gap-3 mb-2"><div className="w-10 h-10 bg-white/20 rounded-lg flex items-center justify-center"><GraduationCap className="h-5 w-5" /></div><div><h1 className="text-base sm:text-2xl font-bold">Brain Courses</h1><p className="text-blue-200 text-xs">Limitless Brain Academy</p></div></div><p className="text-blue-100 text-xs sm:text-sm">Explore curated courses designed to support your brain health journey.</p></div><div className="relative inline-block"><button onClick={() => setOpen(!open)} className="inline-flex items-center gap-2 px-4 py-2 bg-blue-500 text-white rounded-full text-sm">Category <ChevronDown className="h-4 w-4" /></button>{open && <div className="absolute top-full left-0 mt-1 bg-white rounded-lg shadow-lg border py-1 z-10 min-w-[160px]">{categories.map((item) => <button key={item} onClick={() => { setCategory(item); setOpen(false); }} className="block w-full text-left px-4 py-2 text-sm hover:bg-blue-50 capitalize">{item}</button>)}</div>}</div>{loading ? <p className="text-gray-500">Loading courses…</p> : <div className="grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-2 sm:gap-5">{visible.map((course) => { const unlocked = course.is_free || owned.includes(course.id); return <div key={course.id} className="bg-white rounded-lg overflow-hidden shadow-md border flex flex-col"><div className="relative h-28 sm:h-40 bg-gradient-to-br from-[#323956] to-[#5a6490]">{course.thumbnail_url ? <img src={course.thumbnail_url} alt={course.title} className="w-full h-full object-cover" /> : <h3 className="h-full flex items-center justify-center text-white font-bold text-center p-3 text-sm">{course.title}</h3>}{!unlocked && <Lock className="absolute top-2 right-2 h-5 w-5 bg-white/90 rounded-full p-1 text-gray-700" />}</div><div className="p-3 flex flex-col flex-grow"><h4 className="text-sm font-semibold text-gray-900 line-clamp-2 mb-1">{course.title}</h4><p className="text-xs text-gray-500 mb-2">{course.author}</p><div className="mt-auto">{!course.is_free && <div className="flex gap-2 mb-2 text-xs"><span className="text-gray-400 line-through">{course.original_price && money(course.original_price, course.currency)}</span><span className="font-bold text-blue-600">{money(course.sale_price, course.currency)}</span></div>}<button onClick={() => unlocked ? window.open(course.course_url, '_blank', 'noopener,noreferrer') : buy(course)} className={`w-full py-2 rounded-lg text-xs font-medium text-white flex items-center justify-center gap-1 ${unlocked ? 'bg-green-600' : 'bg-[#c9a227]'}`}>{unlocked ? <><ExternalLink className="h-3 w-3" />Open Course</> : <><ShoppingCart className="h-3 w-3" />Buy Now</>}</button></div></div></div>; })}</div>}</div>;
};
export default BrainCourses;
